on:
  workflow_dispatch: {}

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - run: ls -a
    - run: ls -a a/b/c
    - run: cat a/b/c/hello.txt
     