on:
  workflow_dispatch: {}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p a/b/c
    - run: echo "hello" > a/b/c/hello.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: a/b/c/hello.txt