on:
  workflow_dispatch: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p a/b/c
    - run: echo "hello" > a/b/c/hello.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: a/b/c/hello.txt
  add: 
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - run: touch backup.txt
      - run: cat hello.txt > backup.txt
      - uses : actions/upload-artifact@v3
        with:
          name: my-artifact
          path: backup.txt
  download:
    needs: add
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - run: ls -a
    - run: pwd
  checkout:
    needs: download
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ls -a
    - run: pwd
  run:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - run: ls -a
    - run: pwd

     