on:
  workflow_dispatch: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p a/b/c
    - run: echo "hello" > a/b/c/hello.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: a/b/c/hello.txt
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
    - run: ls -a
    - run: ls -a a/b/c
    - run: cat a/b/c/hello.txt
     